version: '3.8'
services:
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:5
    restart: always
    ports:
      - "5555:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=so@sk.com
      - PGADMIN_DEFAULT_PASSWORD=so
    volumes:
      - ./pgadmin:/var/lib/pgadmin
