server:
  port: 2020
  servlet:
    context-path: /change-healthcare
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://localhost:5432/availity
    url: jdbc:postgresql://localhost:5432/postgres
    password: mypostgresql
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
      multipart:
         enabled: true
logging:
  level:
    org:
      hibernate: ERROR
      springframework:
        web: DEBUG

   
